// <auto-generated />
namespace SocialityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddtimetoPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtimetoPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "201505072021391_Add time to Posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
